Add Update main databox repo documentation
me-box/databox pull request #113
Opened 2017-09-27 10:48 UTC by Toshbrown

2017-09-27 11:18 UTC, pooyadav commented
I think this would go in documents.

2017-09-27 11:30 UTC, pooyadav requested changes
There are few typos - also I feel it should go in documents ( as we have all documents are there) and readme.md should be updated accordingly

2017-09-27 11:33 UTC, Toshbrown commented
I'm happy for these to be moved (though it is the convention to have them here).

2017-10-01 18:52 UTC, mor1 commented on CONTRIBUTING.md
> +Found a peroblem? Got a feature request? Then plese open an issue on the main
`peroblem`.

2017-10-01 18:52 UTC, mor1 commented on CONTRIBUTING.md
> +[databox repository](https://github.com/me-box/databox/). First check that
`Databox`

2017-10-01 18:53 UTC, mor1 requested changes
Were these versions of files substantially copied from anywhere? If so, please check licensing and do the appropriate things.

`CONTRIBUTING.md` traditionally goes in the root dir of project (along with a few other things).

2017-10-01 18:53 UTC, mor1 commented on README.md
> +The databox project welcomes contributions via pull requests see [CONTRIBUTING.md](./CONTRIBUTING.md) for more information.
`Databox`

2017-10-01 18:53 UTC, mor1 commented on TESTING.md
> +See the [core-arbitor](https://github.com/me-box/core-arbiter/tree/master/test)
`arbitor`

2017-10-06 07:40 UTC, merged